### ISSUE TITLE
xo misses specification of rule for next-line in xo/no-abusive-eslint-disable

### ISSUE THREAD

**Issue by florianb** [sindresorhus/xo#126]
The following lines:

```
// eslint-disable-next-line import/no-extraneous-dependencies
import electron from 'electron'
```

get wrongly denounced as follows:

```
  src/gui/dimchi.js:0:1
  ✖   0:1  Specify the rules you want to disable at line 3:0       xo/no-abusive-eslint-disable
```

👣  to reproduce:

1. Create a electron-project depending on `electron-prebuilt`
2. Receive a "electron should be listed in the project's dependencies. Run npm i -S electron to add it" by xo
3. Add `// eslint-disable-next-line import/no-extraneous-dependencies` in the line above the indicated import
4. The `no-extraneous-dependencies`-indicator disappears, the `no-abusive-eslint-disable` appears. 🎉

**Comment by florianb** [comment]
Hmm.. i guess this belongs to benmosher/eslint-plugin-import.

**Comment by jfmengels** [comment]
Actually no, the error is due to `sindresorhus/eslint-plugin-xo`, with the `no-abusive-eslint-disable` rule. Didn't know about `eslint-disable-next-line`. Just fixed that in https://github.com/sindresorhus/eslint-plugin-xo/pull/39.

Although the fact that you have to disable `electron` is an issue for benmosher/eslint-plugin-import. There is work ongoing for that ;)

**Comment by florianb** [comment]
@jfmengels: Great! ❤️ 🍻 Thanks a lot, i stay calm.. 😁
