### ISSUE TITLE
Integrate the `prettier` module

### ISSUE THREAD

**Issue by hugomrdias** [sindresorhus/xo#176]
would you consider using or doing something like https://github.com/kentcdodds/prettier-eslint for xo --fix ?

more links 
https://github.com/jlongster/prettier
https://github.com/kentcdodds/prettier-eslint-cli

**Comment by sindresorhus** [comment]
Maybe. I'm gonna give it some time to mature first. Right now it's very buggy. I'll keep this issue open.

**Comment by lydell** [comment]
Relevant: https://github.com/not-an-aardvark/eslint-plugin-prettier

(I use it and think it's great.)

**Comment by Fenwil** [comment]
@sindresorhus we will see this feature in a near feature ? thanks!

**Comment by jangerhofer** [comment]
Heads-up: Prettier has just [hit v1.0](https://github.com/prettier/prettier/releases)!

I found this issue because I do not fully understand what differentiates Prettier from XO.  Wouldn't a Prettier plugin duplicate XO's functionality?

**Comment by Fenwil** [comment]
@jangerhofer Prettier is a formatter and XO is a linter that uses ESLint underneath

**Comment by bfred-it** [comment]
Oh no. Every time I try prettier I don't like its tricks to shorten the lines.

# xo ok

<img width="385" alt="xo" src="https://user-images.githubusercontent.com/1402241/29827358-04b89c0e-8d04-11e7-9399-928a07ffa0d3.png">

# prettier

<img width="385" alt="prettier" src="https://user-images.githubusercontent.com/1402241/29827357-04afce12-8d04-11e7-915d-3475f8b0ebbe.png">


Why.

**Comment by lipis** [comment]
Prettier is really mature now and can be easily integrated.. here is an example on how to use it with ESLint https://github.com/lipis/prettier-setup

**Comment by pvdlg** [comment]
[Prettier](https://github.com/prettier/prettier) is really stable for a while now and used in many large projects (in particular most of Facebook code).

It can be integrated with `xo` or `eslint` pretty easily with [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier):
- `eslint-config-prettier` disable all the `eslint` formatting rules (rules related to comma, spaces etc but not the rules related to code issues) that are covered by `prettier`.
- `eslint-plugin-prettier` report errors/warnings when some code is formatted differently than the `prettier` format and allow to automatically fix it with `--fix`.

In order to use it with `xo` it can be configured this way in `package.json`:
```json
"devDependencies": {
  "eslint-config-prettier": "^2.8.0",
  "eslint-plugin-prettier": "^2.3.0",
  "prettier": "^1.8.2",
  "xo": "^0.18.2"
},
"prettier": {
  // Any other prettier options
  "singleQuote": true
},
"xo": {
  "extends": [
    "prettier"
  ],
  "plugins": [
    "prettier"
  ],
  "rules": {
    "prettier/prettier": "error"
  }
}
```
It works well but it requires some configuration and devDpendencies.

In `xo` we could:
- Add a `prettier` option (`true` or `false`, `false` by default)
- if `prettier` option is `true` add `eslint-plugin-prettier` and `eslint-config-prettier` and the rule ` "prettier/prettier": "error"`

Would you be open to such PR?
