### ISSUE TITLE
Upgrade to eslint v4

### ISSUE THREAD

**Issue by thiamsantos** [sindresorhus/xo#230]
http://eslint.org/blog/2017/06/eslint-v4.0.0-released

I don't know if it will take much work to upgrade.

**Comment by sindresorhus** [comment]
I always wait until at least x.x.1 so I don't have to deal with regressions. I'll keep this open until we upgrade.

**Comment by Nicholaiii** [comment]
@sindresorhus 
4.1.1 is out now as the first x.x.1 since 4.0.0 :) 
http://eslint.org/blog/2017/06/eslint-v4.1.1-released

**Comment by sindresorhus** [comment]
[They have a bunch of regressions with the rewritten `indent` rule.](https://github.com/eslint/eslint/labels/indent) I prefer to wait a little bit more.

**Comment by revelt** [comment]
Just to add my two-pence, the Snyk is reporting XO as having "High severity" [vulnerabilities](https://snyk.io/test/github/sindresorhus/xo) which were solved since v4 ESLint; the latest ESLint [comes clean](https://snyk.io/test/npm/eslint).

![screen shot 2017-09-23 at 19 27 54](https://user-images.githubusercontent.com/8344688/30775956-98f2811a-a095-11e7-82ec-910cd1b7377f.png)

I know being a `dev` dependency it's not a big deal, but badges of all code quality measurement services and Snyk itself look nasty currently.

**Comment by jamestalmage** [comment]
The latest `eslint-config-xo` now relies on `eslint@4`.

Trying to use `xo` with the latest `eslint-config-xo`, I get:

```
Error: /projectDir/node_modules/eslint-config-xo/index.js:
        Configuration for rule "no-else-return" is invalid:
        Value "[object Object]" has more items than allowed.
```

upgrading `xo` to `eslint@4` fixed the problem.

**Comment by sindresorhus** [comment]
The ESLint upgrade was done in https://github.com/sindresorhus/xo/commit/a11e288d7227aa55db6df130d42f3593f8474ded. I plan to do a new release soon.
