### ISSUE TITLE
xo change my console font

### ISSUE THREAD

**Issue by dotmagic** [sindresorhus/xo#263]
I'm using uxterm on Linux and when I start xo it changes the font to some weird monospaced font. I have to close the terminal to reset my fonts. I can reproduce it with xterm, with konsole (KDE) everything seems to be fine.

**Comment by sindresorhus** [comment]
Sounds more like a bug in your terminal. I don't think CLI tools have the ability to change the terminal font directly, and I know for sure XO isn't doing that.

**Comment by dotmagic** [comment]
Well, xterm is the standard terminal for X Window System with millions of installations. Of course it's possible there's such a bug but I can't imagine. Especially since I never had such a problem with stylelint and eslint. It must be rather my configuration for xterm. I will try to track it down and report updates.

**Comment by sholladay** [comment]
I wonder if it could somehow be the symbols or ANSI codes used in the `pretty` formatter:
https://github.com/sindresorhus/eslint-formatter-pretty/blob/e3e80c12955e60a9af49ae7410e4c73450aba452/package.json#L30-L34

Out of curiosity, what happens if you use a different formatter?

My wild guess is that the font you are using doesn't support something in the output and it then falls back to a default font. Not sure if that's even a thing, though.

**Comment by sindresorhus** [comment]
Regardless, I don't think this is an issue with XO.
