### ISSUE TITLE
Automatically ignore directories/files in .gitignore

### ISSUE THREAD

**Issue by dylang** [sindresorhus/xo#27]
To avoid all those pesky babel and electron build dirs.

**Comment by eriknyk** [comment]
+1

**Comment by jamestalmage** [comment]
I think this could be useful. Is there ever a scenario where you would *want* to lint `.gitignore`?

**Comment by sholladay** [comment]
Amen. I really dislike duplicating my `build` and `report` (etc) directories in `xo.ignore` in package.json, when they are already specified in .gitignore. There is existing precedent for looking there as the Single Source of Truth for such things. For example, npm consults .gitignore for the `npm pack` procedure, which is in turn used by `npm publish` and friends.

If XO automatically ignores .gitignore patterns, it will keep our configuration DRY and make projects easier to maintain.

**Comment by vdemedes** [comment]
I like this idea too, looks totally reasonable.

**Comment by sindresorhus** [comment]
Yup, totally, just needs someone willing to do the work, I haven't had time yet.

**Comment by jamestalmage** [comment]
Possibly helpful: https://github.com/jonschlinkert/parse-gitignore

**Comment by sholladay** [comment]
[$40 bounty](https://www.bountysource.com/issues/26773805) because ❤️. xoxo

**Comment by juanj** [comment]
I can help with this.

**Comment by shadiakiki1986** [comment]
Oops I didn't pay attention that juanj was also fixing this. :D  well...

**Comment by sindresorhus** [comment]
Thanks for the bounty @sholladay. You can award it to @juanj :)

**Comment by shadiakiki1986** [comment]
Thanks @juanj for your efforts. I'm very happy that this issue was solved. I just want to vent that I don't think this was completely fair play. Except for the '''nested .gitignores''' and '''cwd option''' requests, my single commit which was made on Sept 30 already had the same code and tests as @juanj 's 17 commits which spanned from Sept 30 to Oct 11. I believe that at least a mention by @juanj is in order about copying the tests from my PR. But again, this isn't really about ownership of code nor about distribution of bounties as it is about collaboration. I'm just happy this got solved anyway.

**Comment by sholladay** [comment]
Hi @shadiakiki1986, I hear you. And I appreciate your work. The purpose of my bounty was to contribute to the community and to encourage people like you to do so, too. I don't want that message to get lost. I will try to find a way to reward you, too. It may take me a few days to get around to it. Likely I will cc you on another issue and award a higher bounty for that then I otherwise would have, while making it obvious it should go to you. Again, thanks for your time.

**Comment by juanj** [comment]
Hey @shadiakiki1986 sorry if I didn't give you credit for that. But I don't copy your test's I just make a copy of one of the existing test and adapt it to test what we need. In the end it result in a very similar test.
Anyway, wish you luck in the next bounty!
