### ISSUE TITLE
Idea: auto-create .eslintrc

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/xo#76]
In-Editor linter plugins like [SublimeLinter-contrib-eslint_d](https://github.com/roadhump/SublimeLinter-contrib-eslint_d) require a `.eslintrc` to be present in the project directory to work. Would it be possible for xo to create one, maybe through a `postinstall` npm script?

**Comment by sindresorhus** [comment]
Anything stopping you from using https://github.com/sindresorhus/atom-linter-xo?

**Comment by silverwind** [comment]
Yes, primarily the fact that it's on Atom (not sold on its performance yet). Also, eslint_d is a big improvment in linting performance for big files, but I guess there might be a Atom plugin around for it.

**Comment by sindresorhus** [comment]
Sorry, I meant https://github.com/sindresorhus/SublimeLinter-contrib-xo.

**Comment by silverwind** [comment]
Oh, I wasn't aware of its existance, thanks! If you're not using `eslint_d` in there yet, you should have a look ;)

**Comment by sindresorhus** [comment]
SublimeLinter-contrib-xo feels fast to me. I use it continuously. Could probably be a tiny bit faster, but I don't think it's worth the complexity and fragileness it adds.

**Comment by silverwind** [comment]
Gave it a try. It works on project using xo's rules, but it also started linting my non-xo projects for some reason. Could it be that plugin doesn't actually check `package.json` if xo is enabled?

**Comment by sindresorhus** [comment]
@silverwind Yes, I hadn't really considered that until today. Just added it to the Atom plugin. Should add it to the Sublime plugin too. Opened an issue: https://github.com/sindresorhus/SublimeLinter-contrib-xo/issues/2

**Comment by silverwind** [comment]
Awesome, thanks!

**Comment by abhisekp** [comment]
And what about webstorm? :cry:

**Comment by sindresorhus** [comment]
@abhisekp https://github.com/sindresorhus/xo/issues/67

**Comment by teehemkay** [comment]
re: WebStorm.  

I think adding a command to XO to emit a `.eslintrc*` config would greatly improve XO's WebStorm integration story. 

Why? Because currently WS can only use ESLint directly. So using XO with WebStorm essentially boils down to configuring ESLint to run like XO.

#67 doesn't do much to automate that integration with WS: it simply provide an outline of all the steps involved in setting up ESLint to work with WebStorm with a config 

Sort of like the [`eject`](https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup)  option in the `create-react-app` tool. 

It seems to me that most of the work is already done in `option-manager.js`

With such a command available, I think that integrating XO with WS would as simple as:

```shell
$ npm install --save-dev xo eslint
$ xo --init --eject ...
 ```

The _ejected_ config would not be used by XO only by the external `eslint`
