### ISSUE TITLE
CLI needs quotes around paths

### ISSUE THREAD

**Issue by mattkrick** [sindresorhus/xo#89]
Reproduction:

`"xo --fix src/**/*.js"` => shallowly lint everything that is 1 folder deep in src.
`"xo --fix 'src/**/*.js'"` => do what you expect it to do (notice the extra quotes)

I thought this was weird because my testing command is `ava ./src/**/__tests___/**/*.js`, which works great without those single quotes, so I expected xo to work similarly. 

CC @wenzowski for figuring out the fix

**Comment by wenzowski** [comment]
@mattkrick I think if you were to use the same pattern with `xo` it would behave as expected since the shell doesn't attempt to expand the expression.

Using bash 3 (osx default) from the root of the meatier repo: 
```
$ list=(src/**/__tests___/**/*.js); echo "${list[@]}"
src/**/__tests___/**/*.js
```
while
```
list=(src/**/*.js); echo "${list[@]}"
src/client/Root.js src/client/client.js src/client/makeStore.js src/server/Html.js src/server/broker.js src/server/createSSR.js src/server/init.js src/server/secrets.js src/server/server.babel.js src/server/server.js src/server/worker.js
```

Perhaps we should consider whether it makes sense for `xo` to recurse directories by default, like `ava` does.

**Comment by joakimbeng** [comment]
This has nothing to do with XO but with your shell. If you use glob patterns without quotes it will be expanded by your shell before running XO (which may cause inconsistencies as you have noted), if using quotes the glob pattern itself is passed to XO and it will to the expanding (a better and more platform independent solution).
